### ISSUE TITLE
Mods need categorization

### ISSUE THREAD

**Issue by shodanx2** [ngld/knossos#35] opened 2021-11-10 09:35 UTC
Opening the explore page a new player (returning player after 20 years)
The vast choice of option is daunting.

A basic categorization of the mods would help greatly.

At minimum, base game or essential mods (at least fs1/fs2/silent threat), in-universe mission packs, alternate universe mission packs, "fix" mods, visual improvement mods and miscellaneous/others

**Comment by ngld** [comment] 2021-11-20 00:52
Duplicate of #4.

**Closed as completed by ngld** 2021-11-20 00:52 UTC
